const AuthActionTypes = {
	FETCH_USER_REQUEST: 'FETCH_USER_REQUEST',
	FETCH_USER_SUCCES: 'FETCH_USER_SUCCES',
	FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
	LOG_OUT_USER: 'LOG_OUT_USER',
};

export default AuthActionTypes;
